version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:14-master
    volumes:
      - directus-postgis-14:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432

volumes:
  directus-postgis-14:
    external: true
