blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/nydelic/nydelic-finances/discussions/new
    about: Share your ideas on how to make Nydelic Finances better.
