version: '3'
services:
  database:
    image: postgis/postgis:14-3.2
    volumes:
      - directus-postgis-14:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    networks:
      - directus
    ports:
      - 5432:5432
  cache:
    image: redis:7.0.2
    networks:
      - directus
  directus:
    image: directus
    build: ./
    ports:
      - 8055:8055
    volumes:
      - ./extensions/dist:/directus/extensions/dist
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '11111111-2222-3333-4444-555555555555'
      SECRET: '66666666-7777-8888-9999-000000000000'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'postgres'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      EMAIL_TRANSPORT: 'smtp'
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
      # EMAIL_SMTP_POOL: ''
      # EMAIL_SMTP_SECURE: ''
      # EMAIL_SMTP_IGNORE_TLS: ''

      ADYEN_HMAC_KEY: ${ADYEN_HMAC_KEY}

      EXTENSIONS_AUTO_RELOAD: 'true'
      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options/#general)
      # PUBLIC_URL: 'https://directus.example.com'
volumes:
  directus-postgis-14:
    external: true
networks:
  directus:
